version: '3'

volumes:
  caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: gcr.io/proven-record-242223/open:latest
    env_file:
      - ./credentials/open/production/django.txt
    command: /start.sh
    volumes:
      - .:/app

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: gcr.io/proven-record-242223/open_traefik:latest
    depends_on:
      - django
    ports:
      # SSL termination happens at the LB layer, all traffic here is http
      - "0.0.0.0:80:80"

#  caddy:
#    build:
#      context: .
#      dockerfile: ./compose/production/caddy/Dockerfile
#    depends_on:
#      - django
#    image: gcr.io/proven-record-242223/open_caddy:latest
#    volumes:
#      - caddy:/root/.caddy
#    ports:
#      - "0.0.0.0:80:80"
#      - "0.0.0.0:443:443"

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: >
      /cloud_sql_proxy -instances=proven-record-242223:us-east1:open-b522b437=tcp:0.0.0.0:5432
      -credential_file /root/.config/senrigan_gcp_sql_access.json
    volumes:
      - ./credentials/open/production/:/root/.config
    ports:
      - 5432:5432

  celeryworker:
    image: gcr.io/proven-record-242223/open:latest
    env_file:
      - ./credentials/open/production/django.txt
    volumes:
      - .:/app
    command: /start-celeryworker.sh

  celerybeat:
    image: gcr.io/proven-record-242223/open:latest
    env_file:
      - ./credentials/open/production/django.txt
    volumes:
      - .:/app
    command: /start-celerybeat.sh

